export const CONFIG_SECRET_ACCESS = 'SECRET_ACCESS';
export const CONFIG_EXPIRE_SECOND_ACCESS = 'EXPIRE_SECOND_ACCESS';
export const CONFIG_SECRET_REFRESH = 'SECRET_REFRESH';
export const CONFIG_EXPIRE_SECOND_REFRESH = 'EXPIRE_SECOND_REFRESH';
